Prefer project-root in favor of project-roots (#105)
dajva/rg.el pull request #148
Opened 2023-01-16 10:27 UTC by jobor

The latter has been deprecated.

If project-root is not bound, use project-roots like before.

2023-01-29 16:11 UTC, dajva requested changes
Thanks for the pr. Sorry for the late reply.
There is an error in the code, otherwise it looks fine. See inline comment for details.

2023-01-29 16:11 UTC, dajva commented on rg.el
> +           (car (project-roots) project)))))
Seems ending parenthesis is at the wrong place.  Should be `(car (project-roots project))`, I believe.

2023-02-01 16:08 UTC, jobor commented on rg.el
> +           (car (project-roots) project)))))
Ouch, sorry. I clearly never tested this code path.
Fixed.

2023-02-01 18:18 UTC, dajva approved these changes

2023-02-01 18:19 UTC, merged