add buffer local var rg-match-positions to record all match positions
dajva/rg.el pull request #172
Opened 2024-06-17 13:49 UTC by liuyinz

with the new var, user can replace  matches  very easily, how about this ? @dajva

2024-06-17 20:50 UTC, liuyinz commented
A simple replace command
```elisp
 (defun rg-replace (to-string)
    "Replace matched result in rg-mode buffer."
    (interactive (list (read-string "Rg replace search pattern with: ")))
    (let ((stop-pos (point)))
      (unwind-protect
          (let* ((keep-asking t)
                 (replace-quit nil))
            (wgrep-change-to-wgrep-mode)
            (catch 'quit
              (dolist (cur-match (seq-filter (lambda (match)
                                               (< stop-pos
                                                  (+ (marker-position (car match))
                                                     (cdr match))))
                                             rg-match-positions))
                (goto-char (car cur-match))
                (let ((replace-p (not keep-asking)))
                  (when keep-asking
                    (catch 'pass
                      (while-let ((key (single-key-description
                                        (read-key (format "Replace match string with %s: (y,n,q,!,.) ?"
                                                          to-string)) t)))
                        (pcase key
                          ((or "q" "C-g" "ESC" ".")
                           (and (string= key ".") (setq replace-p t))
                           (setq stop-pos (point))
                           (setq replace-quit t)
                           (throw 'pass nil))
                          ((or "!" "y" "Y" "SPC")
                           (when (string= key "!")
                             (setq stop-pos (point))
                             (setq keep-asking nil))
                           (setq replace-p t)
                           (throw 'pass nil))
                          ((or "n" "N" "DEL")
                           (throw 'pass nil))))))
                  (when replace-p
                    (let ((begin (marker-position (car cur-match))))
                      (delete-region begin (+ begin (cdr cur-match)))
                      (insert to-string)))
                  (when replace-quit (throw 'quit nil))))))
        (wgrep-finish-edit)
        (goto-char stop-pos))))
```

2024-09-07 15:55 UTC, dajva requested changes
Thanks for the PR and sorry for the slow response. The feature looks fine, just one thing that needs to be fixed before merging.

2024-09-07 15:55 UTC, dajva commented on rg-result.el
> +                (append rg-match-positions
I think we need to be vary of performance here. Appending to the end of the list like this could be slow, especially when searches get large. Can you use the push-nreverse idiom instead?
```elisp
(while condition
  (push elt list))
(nreverse list)
```

2024-09-07 18:25 UTC, liuyinz commented on rg-result.el
> +                (append rg-match-positions
I have fixed the issue and force pushed, please check it

2024-09-08 10:59 UTC, merged

2024-09-08 11:00 UTC, dajva commented on rg-result.el
> +                (append rg-match-positions
Thanks. Everything looks good.