WIP: Truncated search pattern in header
dajva/rg.el pull request #177
Opened 2024-09-17 18:08 UTC by Walheimat

This is an attempt to tackle #164.

It's a bit awkward since it means we need to use a function for the `help-echo` prop that needs to access `rg-cur-search` to access the full search pattern.

Maybe you have a better idea.

2024-09-19 16:45 UTC, dajva commented
Thanks for the PR. I like the feature, might even be something to consider to be enabled by default for some proper limit.
Let's discuss the semantics first. There are some style issues etc that we can discuss after that.

My main concern is that it's hard to discover and hit (with the mouse) the truncation string. I ran this locally and thought there was a bug since I didn't see the full search string when hovering the truncated version. Then I realized I needed to hover the three dots which is part of the same entity visually.
What I think would improve the usability is to have the truncation string as a separate entity of the header line, separated by one space instead of two to indicate that it belongs to the search string. This would make it stand out a bit more and have it's own highlighting that would make it easier to discover and hit IMO. Perhaps a bit trickier to implement though.

The other issue is a keyboard trigger. Since this is emacs we need some way to echo the full search via key binding.

I do think it should be possible to get rid of the help function but the header-line-format is tricky so I can't really give any concrete advice before testing a bit myself. See if I can get around to that.

2024-09-19 20:37 UTC, Walheimat commented
Those are good points, I'll have another go at it soon, thanks.

2024-09-20 18:01 UTC, Walheimat commented
So I just found `truncate-string-to-width` which has some interesting options:

> Truncate string STR to end at column END-COLUMN.
> The optional 3rd arg START-COLUMN, if non-nil, specifies the starting
> column (default: zero); that means to return the characters occupying
> columns START-COLUMN ... END-COLUMN of STR.  Both END-COLUMN and
> START-COLUMN are specified in terms of character display width in the
> current buffer; see `char-width'.
> 
> Since character composition on display can produce glyphs whose
> width is smaller than the sum of `char-width' values of the
> composed characters, this function can produce inaccurate results
> when used in such cases.
> 
> The optional 4th arg PADDING, if non-nil, specifies a padding
> character (which should have a display width of 1) to add at the end
> of the result if STR doesn't reach column END-COLUMN, or if END-COLUMN
> comes in the middle of a character in STR.  PADDING is also added at
> the beginning of the result if column START-COLUMN appears in the
> middle of a character in STR.
> 
> If PADDING is nil, no padding is added in these cases, so
> the resulting string may be narrower than END-COLUMN.
> 
> If ELLIPSIS is non-nil, it should be a string which will replace the
> end of STR (including any padding) if it extends beyond END-COLUMN,
> unless the display width of STR is equal to or less than the display
> width of ELLIPSIS.  If it is non-nil and not a string, then ELLIPSIS
> defaults to `truncate-string-ellipsis', or to three dots when it's nil.
> 
> If ELLIPSIS-TEXT-PROPERTY is non-nil, a too-long string will not
> be truncated, but instead the elided parts will be covered by a
> `display' text property showing the ellipsis.

Unfortunately, using `ellipsis-text-property` does not seem to work in the header line but I'll check if I can either get it to work anyway or build something similar.

2024-09-20 18:41 UTC, Walheimat commented
> The other issue is a keyboard trigger. Since this is emacs we need some way to echo the full search via key binding.

How would you currently do that?

For now I just pushed a change to use the built-in function and apply the help echo to then entire text.

2024-09-25 16:07 UTC, Walheimat commented
So what are the style issues you'd like addressed? And what could be a good default limit?

I'll check if I can add some tests for the new functions in the meanwhile to not tank the coverage.

2024-09-26 08:56 UTC, dajva requested changes

2024-09-26 08:56 UTC, dajva commented on rg-header.el
> +  "The max line length of header line items."
This doc string seems a bit off target. Could we change this to something like: `The max length of header line search string item.`

2024-09-26 09:01 UTC, dajva commented
> And what could be a good default limit?
Not exactly sure. 40-50 seems ok to me to have it not being too much in the way.

2024-09-26 16:20 UTC, Walheimat commented on test/rg-header.el-test.el
> +             "everything…"
Ah! Good catch.

2024-09-26 16:26 UTC, Walheimat commented on rg-header.el
> +              'rg-rerun-change-query #'rg-header--search-help
It would just mean that we wouldn't evaluate it lazily. I'm guessing the performance impact is negligible though. 

If you prefer it that way I can change it.

2024-09-26 16:37 UTC, Walheimat commented
I addressed all your points (I hope) in the latest commit. I will rebase everything into a single commit if you're fine with the changes now.

2024-09-27 09:37 UTC, dajva requested changes
Looks good. Just one thing before it can be merged.

2024-09-27 09:37 UTC, dajva commented on rg-header.el
> +(defcustom rg-header-max-search-string-length 50
Sorry, for being unclear here. I was supposed communicate that we need a keyboard binding for this to be enabled by default.
So if you either add that or keep this as `nil` for now. I suppose binding it to `v` (as in verbose) could make sense in case you want to add that.

2024-09-27 19:09 UTC, Walheimat commented on rg-header.el
> +(defcustom rg-header-max-search-string-length 50
You want a binding in `rg-mode-map` to toggle this?

I think I'd prefer keeping it at `nil` and leave it at the user's discretion to set it to a value they see fit. I think the scenario where they'd run into the search pattern length being an issue is so minute that dedicating a key to truncating it seems a bit big.

***

One thing that we may want to consider is to call this `-string-width` not `string-length`. What do you think?

2024-09-29 16:31 UTC, dajva commented on rg-header.el
> +(defcustom rg-header-max-search-string-length 50
Ok, let's put it as `nil` then. I think I prefer *length* actually. *string-width* gives me associations to pixel width on screen rather than number of characters in a string.

2024-09-30 18:31 UTC, Walheimat commented on rg-header.el
> +(defcustom rg-header-max-search-string-length 50
Alright, pushed (never mind the commit message, I didn't rename after all, just had it ready to go). Let me know if you're fine with it now, then I'll rebase and remove draft status. Thank you.

2024-10-01 17:43 UTC, dajva commented on rg-header.el
> +(defcustom rg-header-max-search-string-length 50
All seems fine. So you can clean up and then I merge

2024-10-02 20:36 UTC, dajva approved these changes

2024-10-02 20:36 UTC, merged

2024-10-02 20:37 UTC, dajva commented
Thanks a lot. Merged.